version: '3.8'

services:
  cassandra:
    image: cassandra:4.1
    container_name: cassandra
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=TestCluster
    volumes:
      - cassandra_data:/var/lib/cassandra
    networks:
      - cassandra-net

  studio:
    image: datastax/dse-studio:latest
    container_name: cassandra-studio
    platform: linux/amd64  # Force amd64 platform on ARM hosts
    environment:
      - DS_LICENSE=accept  # Required license acceptance
    depends_on:
      - cassandra
    ports:
      - "9091:9091"
    networks:
      - cassandra-net

volumes:
  cassandra_data:

networks:
  cassandra-net:
    driver: bridge
